### ISSUE TITLE
If you don't mind can you help?

### ISSUE THREAD

**Issue by Saikatsaha1996** [z3ntu/dtbo-fp3#1]
I checked your kernel dts file your board id https://github.com/msm8953-mainline/linux/blob/e968027725388f10fd4255c82c66ee7bb53258e9/arch/arm64/boot/dts/qcom/sdm632-fairphone-fp3.dts#L17

But when you create dtbo your board id changed.. how can you explain.. actually dear I am facing issues in mainline for my device.. unable to boot for dtabo partition.. device came back to bootloader automatically.. can you share please.. so I can create dtbo & boot in mainline..

Thank you..

This is my msm id https://github.com/Saikatsaha1996/android_kernel_oneplus_sm8350/blob/f4a5b8893fc87d25c9d8a69cd59ce80d1fd1f55c/arch/arm64/boot/dts/vendor/qcom/lahaina-v2.1.dtsi#L6

This is my board id
https://github.com/Saikatsaha1996/android_kernel_oneplus_sm8350/blob/f4a5b8893fc87d25c9d8a69cd59ce80d1fd1f55c/arch/arm64/boot/dts/vendor/qcom/lahaina-mtp-v2.1-overlay.dts#L9

This my stock fdt..
https://raw.githubusercontent.com/Saikatsaha1996/realme-porsche/main/realme-porsche.dts.txt

This is my stock kernel cmdline.. 
![IMG_20230803_075551](https://github.com/z3ntu/dtbo-fp3/assets/72664192/67f89ad2-93ba-4675-a314-d9694c1fde96)

**Comment by z3ntu** [comment]
This thing here is really just a workaround for a relatively broken bootloader on msm8953. On other devices very often you can do `fastboot erase dtbo` and then the bootloader just ignores dtbo and uses just the dtb from the boot image (or vendor_boot if that exists already).

You'll be better off asking for help with sm8350 in the mainline channel linked at https://wiki.postmarketos.org/wiki/Matrix_and_IRC or https://matrix.to/#/#sm8350-mainlining:matrix.org

**Comment by Saikatsaha1996** [comment]
> This thing here is really just a workaround for a relatively broken bootloader on msm8953. On other devices very often you can do `fastboot erase dtbo` and then the bootloader just ignores dtbo and uses just the dtb from the boot image (or vendor_boot if that exists already).
> 
> You'll be better off asking for help with sm8350 in the mainline channel linked at https://wiki.postmarketos.org/wiki/Matrix_and_IRC or https://matrix.to/#/#sm8350-mainlining:matrix.org

Sorry for disturb.. my device header version 3 so boot.img not appended.. and i have vendor_boot partition also.. what should I do ? Dtb should be appended ? dtbo should be erased ? And what should for vendor_boot ? Boot.img should be flash in Vendor_boot also ?Re-asking for header version 3 .. please help.. i tried like 100 times or more.. it very upsetting me... Every time came back to bootloader automatically

**Comment by z3ntu** [comment]
I really don't know how your device behaves so I cannot say anything specific to your device. All devices are weird.

On some newer devices with vendor_boot you can erase both dtbo and vendor_boot and the bootloader is still happy with whatever you give it in boot.img only. So do normal dtb append with `cat arch/arm64/boot/Image.gz your-device.dtb > Image.gz-dtb` , pack it in a boot.img and it should be fine.

**Comment by Saikatsaha1996** [comment]
> I really don't know how your device behaves so I cannot say anything specific to your device. All devices are weird.
> 
> On some newer devices with vendor_boot you can erase both dtbo and vendor_boot and the bootloader is still happy with whatever you give it in boot.img only. So do normal dtb append with `cat arch/arm64/boot/Image.gz your-device.dtb > Image.gz-dtb` , pack it in a boot.img and it should be fine.

I hope you already checked my issues in irc sm8350 mainline..  now i successfully created dtbo.. only work when i used header version 1 or 2.. but my device default header version 3.. now device not back to bootloader with header version 2.. only big issue device randomly rebooting.. 2 or 3 sec black screen then reboot..
